# Generated by Django 2.1.7 on 2019-03-26 15:48

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='aboutimg',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path),
        ),
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='website',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='dribble',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
