# Generated by Django 2.1.7 on 2019-03-26 18:49

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190326_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='clients',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='coffee',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='navbarimg',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path),
        ),
        migrations.AddField(
            model_name='website',
            name='projects',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
