# Generated by Django 2.1.7 on 2019-03-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190326_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='code',
            field=models.TextField(default=1, help_text='Separate the servvices with comma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='design',
            field=models.TextField(default=1, help_text='Separate the servvices with comma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='strategy',
            field=models.TextField(default=1, help_text='Separate the servvices with comma'),
            preserve_default=False,
        ),
    ]
