# Generated by Django 2.1.7 on 2019-03-26 19:54

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190326_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Website')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Website')),
            ],
        ),
    ]
