# Generated by Django 2.1.7 on 2019-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_blog_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
