# Generated by Django 2.1.7 on 2019-03-26 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 26, 20, 31, 7, 117943, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
